# Numpy

In [2]:
import numpy as np
a = np.array(([1,2],[3,4]))

a

array([[1, 2],
       [3, 4]])

## basic indexing

In [3]:
x = np.arange(5,10)
x

array([5, 6, 7, 8, 9])

In [4]:
x[-2]

np.int64(8)

## basic slicing and striding

In [5]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])    # np.arange(10)

In [11]:
x[1:8:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
x[1:5:3]   #i,j,k :  i is the starting index, j is the stopping index, and k is the step 

array([1, 4])

In [20]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [18]:
x[:4]

array([0, 1, 2, 3])

In [19]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[-1]

9

In [21]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [22]:
x[-3:]

array([7, 8, 9])

In [34]:
x[[4,2]]

array([4, 2])

## advanced indexing

Integer array indexing

In [31]:
x = np.arange(5,15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [32]:
print(x[np.array([4,2])])
print(x[[4,2]])

[9 7]
[9 7]


## repeat

In [35]:
a = np.array(([1,2],[3,4]))
a.shape

(2, 2)

In [36]:
np.repeat(a, 3,axis=1) # axis repeat with columns

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [ ]:
np.repeat(a, 2,axis=0) # axis repeat with row

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [ ]:
np.repeat(a, 2,axis=-1) # Uses last axis 

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

## flatten

In [17]:
print(a)
a.flatten() # Converts it into 1D

[[1 2]
 [3 4]]


array([1, 2, 3, 4])

In [18]:
b = np.array(([5,6],[7,8]))
b

array([[5, 6],
       [7, 8]])

## concatenate

In [39]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [19]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## transpose

In [ ]:
np.transpose(a)
a.transpose()
a.T

array([[1, 3],
       [2, 4]])

## reshape

In [71]:
z= np.arange(6)
z

array([0, 1, 2, 3, 4, 5])

In [79]:
z.reshape(-1,)

array([0, 1, 2, 3, 4, 5])

In [ ]:
print(z.reshape(2,3)) # m*n needs to match # of elements
z.reshape(2,-1) # -1 automatically matches the given dimension

[[0 1 2]
 [3 4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
np.arange(12).reshape((4,-1,3))

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

In [31]:
a = np.array([[1,2,3], [4,5,6]])
display(np.reshape(a,(6,)))
display(np.reshape(a,(6,-1)))
np.reshape(a,(6,1))

array([1, 2, 3, 4, 5, 6])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
np.reshape(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.reshape(a, (3,-1,))

array([[1, 2],
       [3, 4],
       [5, 6]])

## squeeze

remove axes of length one from input

In [32]:
t = np.arange(6)
t.shape

(6,)

In [33]:
t = np.reshape(t,(6,-1))
print(t)
t.shape #2D array

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [41]:
display(np.squeeze(t.reshape(-1,6)))
np.squeeze(t.reshape(3,2))

array([0, 1, 2, 3, 4, 5])

array([[0, 1],
       [2, 3],
       [4, 5]])

In [35]:
print(np.squeeze(t))
np.squeeze(t).shape

[0 1 2 3 4 5]


(6,)

## stack

Join a sequence of arrays along a new axis.

In [ ]:
array = np.random.randn(3, 4) 
print(array.shape)
array

(3, 4)


array([[ 0.279637  , -0.83426873,  1.74764806,  0.68510199],
       [-0.73803189,  0.38357667,  0.34281658, -0.87232189],
       [-0.16703226, -0.78737057, -0.43231712,  1.83383755]])

In [4]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
arrays

[array([[-1.94886754,  0.40937875,  1.60899137,  1.7048631 ],
        [ 0.9513661 ,  1.15992903, -0.65777788, -1.46538524],
        [ 1.75300271, -2.15901906,  0.2506092 , -1.63243314]]),
 array([[ 0.2903172 ,  0.32376734,  1.28478364, -0.54036321],
        [-0.03999299,  1.90323875, -0.73702404,  2.06340718],
        [ 1.06112371, -1.43964357,  1.50103902,  1.13905873]]),
 array([[ 0.56588159, -1.23223649, -0.27634588, -0.20124593],
        [-0.33605094, -1.33508246, -0.20465654, -2.57782292],
        [ 0.32162114,  0.01193146,  0.92513283,  0.23827719]]),
 array([[-0.50594884,  0.73506077,  1.0883247 ,  0.25717403],
        [ 0.43754689, -1.40423801, -0.92635776, -0.80650187],
        [-1.541007  ,  1.55601468, -0.05171252, -2.76517414]]),
 array([[ 1.68212888,  0.83177503, -0.56373449,  0.62434781],
        [-0.34113796, -0.02355137,  0.33866104,  1.07397125],
        [-1.51761698,  0.49705609, -1.57250838,  0.68392099]]),
 array([[ 0.74381897,  0.49155158, -0.21247516, -0.94007998]

In [4]:
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [5]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [6]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

In [50]:
x = np.array([1,2,3,4]).reshape(2,2)
y = np.arange(5,9).reshape(2,2)

np.stack((x,y),axis=-1)
np.vstack((x,y))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

## vstack

stack arrays in sequence vertically (row wise)

In [85]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [90]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [55]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## hstack

Stack arrays in sequence horizontally (column wise)

In [51]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [56]:
np.stack((a,b),axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [7]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

In [ ]:
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

## Split

Split an array into multiple sub-arrays as views into array.

In [98]:
x = np.arange(9.0)

In [61]:
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [99]:
np.split(x, 4) # Not evenly distributed 

ValueError: array split does not result in an equal division

In [100]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

## flip

Reverse the order of elements in an array along the given axis.

The shape of the array is preserved, but the elements are reordered.

In [102]:
A = np.arange(8).reshape((2,2,2))
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
np.flip(A,axis=0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])

In [104]:
np.flip(A,1)

array([[[2, 3],
        [0, 1]],

       [[6, 7],
        [4, 5]]])

In [105]:
np.flip(A,axis=2)

array([[[1, 0],
        [3, 2]],

       [[5, 4],
        [7, 6]]])

## trim_zeros

Trim the leading and/or trailing zeros from a 1-D array or sequence.

In [16]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))

In [107]:
np.trim_zeros(a) # default: trimming both sides

array([1, 2, 3, 0, 2, 1])

In [108]:
np.trim_zeros(a,'f') # fowrard trimming

array([1, 2, 3, 0, 2, 1, 0])

In [109]:
np.trim_zeros(a,'b') # backward trimming

array([0, 0, 0, 1, 2, 3, 0, 2, 1])

In [12]:
np.ma.masked_equal(a,0) # masking the matching values

masked_array(
  data=[[1],
        [2],
        [3]],
  mask=False,
  fill_value=0)

In [20]:
a[a==0] = 99
a

array([99, 99, 99,  1,  2,  3, 99,  2,  1, 99])