# Numpy

In [1]:
import numpy as np
a = np.array(([1,2],[3,4]))

a

array([[1, 2],
       [3, 4]])

## basic indexing

In [2]:
x = np.arange(5,10)
x

array([5, 6, 7, 8, 9])

In [5]:
x[-2]

np.int64(8)

## basic slicing and striding

In [6]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])    # np.arange(10)

In [7]:
x[1:7:3]   #i,j,k :  i is the starting index, j is the stopping index, and k is the step 

array([1, 4])

In [15]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [18]:
x[:4]

array([0, 1, 2, 3])

In [19]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[-1]

9

In [21]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [22]:
x[-3:]

array([7, 8, 9])

## advanced indexing

Integer array indexing

In [26]:
x = np.arange(5,15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
print(x[np.array([4,2])])
print(x[[4,2]])

[4 2]
[4 2]


## repeat

In [10]:
a = np.array(([1,2],[3,4]))
a.shape

(2, 2)

In [ ]:
np.repeat(a, 3,axis=1) # axis repeat with columns

array([[1, 1, 1, 2, 2, 2],
       [3, 3, 3, 4, 4, 4]])

In [ ]:
np.repeat(a, 2,axis=0) # axis repeat with row

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [ ]:
np.repeat(a, 2,axis=-1) # Uses last axis 

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

## flatten

In [ ]:
print(a)
a.flatten() # Converts it into 1D

[[1 2]
 [3 4]]


array([1, 2, 3, 4])

In [17]:
b = np.array(([5,6],[7,8]))
b

array([[5, 6],
       [7, 8]])

## concatenate

In [39]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [ ]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## transpose

In [ ]:
np.transpose(a)
a.transpose()
a.T

array([[1, 3],
       [2, 4]])

## reshape

In [24]:
z= np.arange(6)
z

array([0, 1, 2, 3, 4, 5])

In [28]:
print(z.reshape(2,3)) # m*n needs to matches # of elements
z.reshape(2,-1) # -1 automatically matches the given dimension

[[0 1 2]
 [3 4 5]]


array([[0, 1, 2],
       [3, 4, 5]])

In [27]:
np.arange(12).reshape((2,-1,3))

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [29]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a,6)

array([1, 2, 3, 4, 5, 6])

In [50]:
np.reshape(a, (3,2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
np.reshape(a, (3,-1,))

array([[1, 2],
       [3, 4],
       [5, 6]])

## squeeze

remove axes of length one from input

In [36]:
t = np.arange(6)
t.shape

(6,)

In [40]:
t = np.reshape(t,(6,1))
print(t)
t.shape #2D array

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [43]:
print(np.squeeze(t))
np.squeeze(t).shape

[0 1 2 3 4 5]


(6,)

## stack

Join a sequence of arrays along a new axis.

In [46]:
array = np.random.randn(3, 4) 
array

array([[ 0.234665  ,  1.01470735,  1.76725501,  1.00118649],
       [-1.09912225,  1.31760224,  0.63017787,  2.30209832],
       [-0.23624804,  1.72496449,  0.81404041,  0.69726061]])

In [47]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
arrays

[array([[ 0.40231169,  2.14008861, -0.52187794,  1.78963045],
        [ 0.42215558, -0.13360446,  1.80426216, -0.17066103],
        [ 0.87331888,  0.49144719, -1.42992523,  0.64453768]]),
 array([[-0.14479508, -0.65642703, -1.06984239,  0.25695513],
        [-1.94001055,  2.5498494 ,  1.19669585,  0.54613436],
        [ 0.39826242,  0.67105394,  1.37694083,  0.36476325]]),
 array([[-0.55065278, -0.90733533, -0.53416723,  0.094436  ],
        [ 1.72198678, -0.3255869 ,  1.75130296,  1.36288987],
        [-1.81118693,  0.5146618 , -1.90582251,  1.13012033]]),
 array([[ 0.44648996,  0.64109302,  1.07431598, -0.52535063],
        [ 1.52936831, -0.02056776, -1.23271454, -0.52685789],
        [ 0.21266457,  0.96910161,  0.37371111, -0.40727437]]),
 array([[-1.24295108, -1.10920171, -0.19521668,  1.29327807],
        [ 0.0989148 ,  0.59813463,  0.9213658 , -2.12032835],
        [-0.31004643, -0.90767572,  0.61051765, -1.12091182]]),
 array([[ 0.77832713,  1.04863979,  0.27516194,  0.91243378]

In [49]:
arrays

[array([[ 0.40231169,  2.14008861, -0.52187794,  1.78963045],
        [ 0.42215558, -0.13360446,  1.80426216, -0.17066103],
        [ 0.87331888,  0.49144719, -1.42992523,  0.64453768]]),
 array([[-0.14479508, -0.65642703, -1.06984239,  0.25695513],
        [-1.94001055,  2.5498494 ,  1.19669585,  0.54613436],
        [ 0.39826242,  0.67105394,  1.37694083,  0.36476325]]),
 array([[-0.55065278, -0.90733533, -0.53416723,  0.094436  ],
        [ 1.72198678, -0.3255869 ,  1.75130296,  1.36288987],
        [-1.81118693,  0.5146618 , -1.90582251,  1.13012033]]),
 array([[ 0.44648996,  0.64109302,  1.07431598, -0.52535063],
        [ 1.52936831, -0.02056776, -1.23271454, -0.52685789],
        [ 0.21266457,  0.96910161,  0.37371111, -0.40727437]]),
 array([[-1.24295108, -1.10920171, -0.19521668,  1.29327807],
        [ 0.0989148 ,  0.59813463,  0.9213658 , -2.12032835],
        [-0.31004643, -0.90767572,  0.61051765, -1.12091182]]),
 array([[ 0.77832713,  1.04863979,  0.27516194,  0.91243378]

In [48]:
np.stack(arrays, axis=0).shape

(10, 3, 4)

In [50]:
np.stack(arrays, axis=1).shape

(3, 10, 4)

In [51]:
np.stack(arrays, axis=2).shape

(3, 4, 10)

## vstack

stack arrays in sequence vertically (row wise)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [53]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [54]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [55]:
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

## hstack

Stack arrays in sequence horizontally (column wise)

In [56]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [57]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [58]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

In [59]:
np.hstack((a,b))

array([[1, 4],
       [2, 5],
       [3, 6]])

## Split

Split an array into multiple sub-arrays as views into array.

In [60]:
x = np.arange(9.0)

In [61]:
np.split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [ ]:
np.split(x, 4) # Not evenly distributed 

In [62]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

[array([0., 1., 2.]),
 array([3., 4.]),
 array([5.]),
 array([6., 7.]),
 array([], dtype=float64)]

## flip

Reverse the order of elements in an array along the given axis.

The shape of the array is preserved, but the elements are reordered.

In [ ]:
A = np.arange(8).reshape((2,2,2))

In [ ]:
A

In [ ]:
np.flip(A,0)

In [ ]:
np.flip(A,1)

In [ ]:
np.flip(A,2)

## trim_zeros

Trim the leading and/or trailing zeros from a 1-D array or sequence.

In [63]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))

In [ ]:
np.trim_zeros(a) # default: trimming both sides

array([1, 2, 3, 0, 2, 1])

In [67]:
np.trim_zeros(a,'f') # fowrard trimming

array([1, 2, 3, 0, 2, 1, 0])

In [66]:
np.trim_zeros(a,'b') # backward trimming

array([0, 0, 0, 1, 2, 3, 0, 2, 1])

In [ ]:
np.ma.masked_equal(a,0) # masking the matching values

masked_array(data=[--, --, --, 1, 2, 3, --, 2, 1, --],
             mask=[ True,  True,  True, False, False, False,  True, False,
                   False,  True],
       fill_value=0)