# Movie-Lens 100k Dataset

## Data Import

In [2]:
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/han942/vscode/refs/heads/main/datafile/Recsys/ml-100k/u.data',sep='\t',
                   names=['userID','movieID','ratings','timestamp'])
data.head()

userID  movieID  ratings  timestamp
0     196      242        3  881250949
1     186      302        3  891717742
2      22      377        1  878887116
3     244       51        2  880606923
4     166      346        1  886397596

In [3]:
a="unknown | Action | Adventure | Animation | Children's | Comedy | Crime | Documentary | Drama | Fantasy | Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi | Thriller | War | Western |"
a.replace(' |','').split()

['unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [4]:
#각 index가 ID가 됨.
items = pd.read_csv('https://raw.githubusercontent.com/han942/vscode/refs/heads/main/datafile/Recsys/ml-100k/u.item',encoding='latin-1',
                    sep='|',header=None,names=['movieID','title','release_date','video_release_date','URL','unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western'])

In [5]:
items

movieID                                      title release_date  \
0           1                           Toy Story (1995)  01-Jan-1995   
1           2                           GoldenEye (1995)  01-Jan-1995   
2           3                          Four Rooms (1995)  01-Jan-1995   
3           4                          Get Shorty (1995)  01-Jan-1995   
4           5                             Copycat (1995)  01-Jan-1995   
...       ...                                        ...          ...   
1677     1678                          Mat' i syn (1997)  06-Feb-1998   
1678     1679                           B. Monkey (1998)  06-Feb-1998   
1679     1680                       Sliding Doors (1998)  01-Jan-1998   
1680     1681                        You So Crazy (1994)  01-Jan-1994   
1681     1682  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      video_release_date                                                URL  \
0                    NaN  http://us.imdb.com/M/title-exact?Toy%20Story%2...   
1                    NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...   
2                    NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...   
3                    NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...   
4                    NaN  http://us.imdb.com/M/title-exact?Copycat%20(1995)   
...                  ...                                                ...   
1677                 NaN  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...   
1678                 NaN  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...   
1679                 NaN      http://us.imdb.com/Title?Sliding+Doors+(1998)   
1680                 NaN  http://us.imdb.com/M/title-exact?You%20So%20Cr...   
1681                 NaN  http://us.imdb.com/M/title-exact?Schrei%20aus%...   

      unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
0           0       0          0          1           1  ...        0   
1           0       1          1          0           0  ...        0   
2           0       0          0          0           0  ...        0   
3           0       1          0          0           0  ...        0   
4           0       0          0          0           0  ...        0   
...       ...     ...        ...        ...         ...  ...      ...   
1677        0       0          0          0           0  ...        0   
1678        0       0          0          0           0  ...        0   
1679        0       0          0          0           0  ...        0   
1680        0       0          0          0           0  ...        0   
1681        0       0          0          0           0  ...        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1677          0       0        0        0        0       0         0    0   
1678          0       0        0        0        1       0         1    0   
1679          0       0        0        0        1       0         0    0   
1680          0       0        0        0        0       0         0    0   
1681          0       0        0        0        0       0         0    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1677        0  
1678        0  
1679        0  
1680        0  
1681        0  

[1682 rows x 24 columns]

In [6]:
users = pd.read_csv('https://raw.githubusercontent.com/han942/vscode/refs/heads/main/datafile/Recsys/ml-100k/u.user',sep='|',
                   names=['userID','age','gender','occupation','zipcode'])
users.head()

userID  age gender  occupation zipcode
0       1   24      M  technician   85711
1       2   53      F       other   94043
2       3   23      M      writer   32067
3       4   24      M  technician   43537
4       5   33      F       other   15213

In [ ]:
df = pd.merge(data,items.iloc[:,:2],on='movieID')
user_movie_matrix = pd.pivot_table(data=df,index='userID',columns='movieID',values='ratings')
user_movie_matrix_na = user_movie_matrix.fillna(0)

In [8]:
user_movie_matrix #Sparse Matrix (희소행렬)

movieID  1     2     3     4     5     6     7     8     9     10    ...  \
userID                                                               ...   
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2         4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5         4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   
940       NaN   NaN   NaN   2.0   NaN   NaN   4.0   5.0   3.0   NaN  ...   
941       5.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
943       NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   

movieID  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
userID                                                               
1         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
940       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
941       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
943       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[943 rows x 1682 columns]

## Collaborative Filtering

### User-Based Filtering
1. Find Similarity Score btw different users
2. For Target User, Set Neighbors ($K$) to refer
3. Find the Neighbor Similarity Score
4. For Target Items, Predict Ratings for the unknown
    - Compution only needs to be done using observed ratings

$$prediction(a,p) = \bar{r_a} + \frac{\sum{sim(a,b)}*(r_{b,p}-\bar{r_b})}{\sum{|sim(a,b)|}}$$

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
user_movie_matrix = pd.pivot_table(data=df,index='userID',columns='movieID',values='ratings')
user_movie_matrix_na = user_movie_matrix.fillna(0)

user_cos = cosine_similarity(user_movie_matrix_na)

In [9]:
print('영화1의 rating 평균',user_movie_matrix[1].mean())
print('user1의 rating 평균',user_movie_matrix.loc[1].mean())

영화1의 rating 평균 3.8783185840707963
user1의 rating 평균 3.610294117647059


In [10]:
user_movie_matrix_nu = user_movie_matrix_na.to_numpy()

In [38]:
#특정 user_id에 대해 전체 참고
import numpy as np
new_p = user_movie_matrix.copy()

def prediction(user_id,p,b,new_p):
    new_p.loc[user_id,p] = user_movie_matrix_nu[user_id-1].mean() + np.sum(user_cos[user_id-1,b-1] * (user_movie_matrix_nu[b-1,p-1] - user_movie_matrix_nu[b-1].mean())) / np.sum(np.abs(user_cos[user_id-1,b-1]))
user_id = 13
for p in range(1,(len(user_movie_matrix.columns.values)+1)):
    for b in range(1,(len(user_movie_matrix.index.values)+1)):
        if user_movie_matrix_na.loc[user_id,p] == 0:
            if b == user_id:
                pass
            prediction(user_id,p,b,new_p)

KeyboardInterrupt: 

### Item Based CF

## Latent Factor Models

### SVD(MF,Matrix Factorization)

#### 방법1. 기존의 MF 방법
1. 정규분포를 따르는 무작위의 숫자로 구성된 User / Item Latent Matrix P,Q를 구성
2. Nan값이 아닌 Rating을 Test $P,Q^T$의 내적값을 predict로 정의
3. 두 값 사이의 Error를 구해서 Objective Function에 맞는 Optimization 진행
4. 모든 값을 Update 후에 2)~4)의 과정 반복
$$\text{Dimension Guide : } \\ R(m*n),P(m*k),Q(n*k) $$

In [ ]:
import numpy as np
R = np.array(user_movie_matrix)
n_users,n_items = user_movie_matrix.shape
k = 30
P = np.random.normal(scale=0.1/k, size=(n_users,k))
Q = np.random.normal(scale=0.1/k, size=(n_items,k))
epochs = 500
lr = 0.03   #높이면 에러 뜨는듯
reg_param = 0.02 #0.01~0.1
not_nan_ind = [(i,j) for i in range(n_users) for j in range(n_items) if R[i,j]>0]

for epoch in range(epochs):
    np.random.shuffle(not_nan_ind)
    for i,j in not_nan_ind:
        error = R[i,j] - np.dot(P[i,:],Q[j,:].T)
        P[i,:] += lr * (error * Q[j,:] - reg_param * P[i,:])
        Q[j,:] += lr * (error * P[i,:] - reg_param * Q[j,:])
    if epoch % 100 == 0:
        loss = np.sum([((R[i,j]-np.dot(P[i,:],Q[j,:].T))**2) for i,j in not_nan_ind])
        rmse = np.sqrt(loss / len(not_nan_ind))
        print(f"Epoch: {epoch}, Loss: {loss:.4f}, RMSE: {rmse:.4f}")

R_hat = np.dot(P,Q.T)
print("\n예측된 평점 행렬")
print(np.round(R_hat,3))

Epoch: 0, Loss: 112261.4400, RMSE: 1.0595
Epoch: 100, Loss: 23419.2776, RMSE: 0.4839
Epoch: 200, Loss: 22611.6325, RMSE: 0.4755
Epoch: 300, Loss: 22650.6541, RMSE: 0.4759
Epoch: 400, Loss: 22511.5674, RMSE: 0.4745

예측된 평점 행렬
[[3.84 3.19 4.08 ... 1.05 1.69 2.91]
 [3.94 2.91 1.25 ... 0.89 1.89 2.49]
 [3.91 2.87 0.84 ... 1.05 1.12 1.74]
 ...
 [4.74 3.66 2.27 ... 1.16 2.26 2.23]
 [4.62 4.33 4.87 ... 0.8  1.92 2.33]
 [4.03 4.52 1.52 ... 1.21 2.   2.28]]


#### 방법2. Tensorflow 이용
$$ \text{update rule} \\  b_u \leftarrow b_u + \eta*(e_{u,i}-\lambda b_u)\\ p_u \leftarrow p_u+\eta(e_{u,i}q_i-\lambda p_u) $$

In [ ]:
import tensorflow as tf
import numpy as np

R = np.array(user_movie_matrix,dtype='float32')
n_users,n_items = R.shape
lr = 0.0005
K = 30
reg_param = 0.01
epochs = 500

obs_ind = np.array([(i,j) for i in range(n_users) for j in range(n_items) if R[i,j]>0])

P = tf.Variable(tf.random.normal([n_users,K],stddev=0.1),dtype=np.float32)  #Latent Feature Extraction (K)
Q = tf.Variable(tf.random.normal([n_items,K],stddev=0.1),dtype=np.float32)

def predict():
    return tf.matmul(P,Q,transpose_b=True)
def loss_fn():
    pred = predict()
    pred_val = tf.gather_nd(pred,obs_ind)
    R_val = tf.gather_nd(R,obs_ind)
    
    error = R_val - pred_val
    rmse = tf.sqrt(tf.reduce_mean(tf.square(error)))
    loss = tf.reduce_sum(tf.square(error)) #Loss 함수만 제대로 정의하면, Gradient Descent는 따로 정의할 필요 X
    reg_loss = reg_param * (tf.nn.l2_loss(P)+tf.nn.l2_loss(Q))
    
    return loss + reg_loss,rmse
opt = tf.keras.optimizers.SGD(learning_rate=lr)

for epoch in range(epochs+1):
    with tf.GradientTape() as tape:
        loss,rmse = loss_fn()
    grad = tape.gradient(loss,[P,Q])  
    opt.apply_gradients(zip(grad,[P,Q]))
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss:{loss.numpy():.4f}, RMSE:{rmse.numpy():.4f}")

R_pred = predict().numpy()
print("\nPredicted R:")
print(np.round(R_pred,2))

Epoch 0, Loss:1373340.6250, RMSE:3.7059
Epoch 100, Loss:71959.8906, RMSE:0.8480
Epoch 200, Loss:46132.8242, RMSE:0.6788
Epoch 300, Loss:34867.3672, RMSE:0.5899
Epoch 400, Loss:29783.9961, RMSE:0.5451

Predicted R:
[[4.65 3.49 3.64 ... 0.11 1.43 2.76]
 [4.06 2.61 2.34 ... 0.45 1.64 1.8 ]
 [2.85 2.27 2.03 ... 0.6  0.71 1.7 ]
 ...
 [4.8  3.47 3.05 ... 0.5  1.4  2.43]
 [4.2  3.94 4.16 ... 0.47 1.94 1.96]
 [2.75 4.21 2.63 ... 0.23 1.5  2.28]]


In [83]:
R_hat[obs_ind[:, 0], obs_ind[:, 1]]

array([3.84221032, 3.18630686, 4.07879787, ..., 3.25957289, 2.92816931,
       3.17635855])

In [82]:
R[obs_ind[:,0],obs_ind[:,1]]

array([5., 3., 4., ..., 3., 3., 3.], dtype=float32)

In [48]:
pd.DataFrame(R_hat)

0         1         2         3         4         5         6     \
0    3.842210  3.186307  4.078798  3.277075  2.425770  4.627774  4.314092   
1    3.941109  2.906886  1.248711  2.794573  3.486477  6.364288  4.735579   
2    3.905778  2.867288  0.837670  3.322021  2.833766  1.401537  1.664753   
3    6.002248  3.791917  1.476905  2.692198  3.531877  3.173924  4.933363   
4    4.255481  2.646312  1.572110  4.351764  2.181791  0.682968  5.424307   
..        ...       ...       ...       ...       ...       ...       ...   
938  4.757261  3.645577  3.472136  3.067003  4.760345  5.543251  5.035142   
939  4.719337  3.684262  2.620059  1.666491  3.874476  2.042350  3.649159   
940  4.739416  3.664250  2.274834  4.836001  2.355996  3.514223  4.157296   
941  4.617290  4.326902  4.866071  3.137980  5.250616  4.784536  4.332650   
942  4.033016  4.518140  1.517134  4.545488  5.290024  1.464241  3.385891   

         7         8         9     ...      1672      1673      1674  \
0    2.750300  4.163011  3.475199  ...  2.164038  2.833960  2.246556   
1    3.608734  4.438494  2.235896  ...  2.189226  2.937809  1.893957   
2    2.997655  2.917529  2.752301  ...  1.832032  2.520991  2.123741   
3    5.843069  4.559049  7.364062  ...  2.383067  3.556861  1.964500   
4    3.916420  1.336611  5.413658  ...  1.727275  2.599646  2.069641   
..        ...       ...       ...  ...       ...       ...       ...   
938  4.300088  5.124732  3.243833  ...  2.753879  3.579606  2.334358   
939  4.119472  3.326556  5.108322  ...  1.701470  2.434846  1.844637   
940  5.148869  3.603056  4.604482  ...  1.956350  3.101785  2.485327   
941  5.434126  5.207678  3.810183  ...  2.412804  3.327042  2.154732   
942  4.033454  3.962058  5.940854  ...  2.202218  3.173537  2.524018   

         1675      1676      1677      1678      1679      1680      1681  
0    1.479291  2.148278  0.535523  1.655119  1.054636  1.692033  2.910398  
1    1.248900  2.074184  0.444242  1.409121  0.894579  1.889698  2.486799  
2    1.408205  1.169954  0.534718  1.620812  1.050690  1.118632  1.736756  
3    1.298474  2.748446  0.515447  1.627415  1.038047  1.982686  2.231471  
4    1.366494  2.130700  0.407885  1.289002  0.815832  1.332897  1.823416  
..        ...       ...       ...       ...       ...       ...       ...  
938  1.538449  2.029857  0.680213  2.105775  1.361830  1.759082  2.471763  
939  1.212677  2.114848  0.382880  1.250054  0.795422  1.433940  1.634360  
940  1.643309  1.905089  0.579668  1.807166  1.163239  2.261657  2.225026  
941  1.428018  1.789904  0.401425  1.281511  0.802237  1.921522  2.331867  
942  1.676271  2.116345  0.587902  1.868053  1.210211  1.996441  2.279404  

[943 rows x 1682 columns]