# Movie-Lens 100k Dataset

## Data Import

In [4]:
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/han942/vscode/refs/heads/main/datafile/Recsys/ml-100k/u.data',sep='\t',
                   names=['userID','movieID','ratings','timestamp'])
data.head()

userID  movieID  ratings  timestamp
0     196      242        3  881250949
1     186      302        3  891717742
2      22      377        1  878887116
3     244       51        2  880606923
4     166      346        1  886397596

In [5]:
a="unknown | Action | Adventure | Animation | Children's | Comedy | Crime | Documentary | Drama | Fantasy | Film-Noir | Horror | Musical | Mystery | Romance | Sci-Fi | Thriller | War | Western |"
a.replace(' |','').split()

['unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western']

In [6]:
#각 index가 ID가 됨.
items = pd.read_csv('https://raw.githubusercontent.com/han942/vscode/refs/heads/main/datafile/Recsys/ml-100k/u.item',encoding='latin-1',
                    sep='|',header=None,names=['movieID','title','release_date','video_release_date','URL','unknown',
 'Action',
 'Adventure',
 'Animation',
 "Children's",
 'Comedy',
 'Crime',
 'Documentary',
 'Drama',
 'Fantasy',
 'Film-Noir',
 'Horror',
 'Musical',
 'Mystery',
 'Romance',
 'Sci-Fi',
 'Thriller',
 'War',
 'Western'])

In [7]:
items

movieID                                      title release_date  \
0           1                           Toy Story (1995)  01-Jan-1995   
1           2                           GoldenEye (1995)  01-Jan-1995   
2           3                          Four Rooms (1995)  01-Jan-1995   
3           4                          Get Shorty (1995)  01-Jan-1995   
4           5                             Copycat (1995)  01-Jan-1995   
...       ...                                        ...          ...   
1677     1678                          Mat' i syn (1997)  06-Feb-1998   
1678     1679                           B. Monkey (1998)  06-Feb-1998   
1679     1680                       Sliding Doors (1998)  01-Jan-1998   
1680     1681                        You So Crazy (1994)  01-Jan-1994   
1681     1682  Scream of Stone (Schrei aus Stein) (1991)  08-Mar-1996   

      video_release_date                                                URL  \
0                    NaN  http://us.imdb.com/M/title-exact?Toy%20Story%2...   
1                    NaN  http://us.imdb.com/M/title-exact?GoldenEye%20(...   
2                    NaN  http://us.imdb.com/M/title-exact?Four%20Rooms%...   
3                    NaN  http://us.imdb.com/M/title-exact?Get%20Shorty%...   
4                    NaN  http://us.imdb.com/M/title-exact?Copycat%20(1995)   
...                  ...                                                ...   
1677                 NaN  http://us.imdb.com/M/title-exact?Mat%27+i+syn+...   
1678                 NaN  http://us.imdb.com/M/title-exact?B%2E+Monkey+(...   
1679                 NaN      http://us.imdb.com/Title?Sliding+Doors+(1998)   
1680                 NaN  http://us.imdb.com/M/title-exact?You%20So%20Cr...   
1681                 NaN  http://us.imdb.com/M/title-exact?Schrei%20aus%...   

      unknown  Action  Adventure  Animation  Children's  ...  Fantasy  \
0           0       0          0          1           1  ...        0   
1           0       1          1          0           0  ...        0   
2           0       0          0          0           0  ...        0   
3           0       1          0          0           0  ...        0   
4           0       0          0          0           0  ...        0   
...       ...     ...        ...        ...         ...  ...      ...   
1677        0       0          0          0           0  ...        0   
1678        0       0          0          0           0  ...        0   
1679        0       0          0          0           0  ...        0   
1680        0       0          0          0           0  ...        0   
1681        0       0          0          0           0  ...        0   

      Film-Noir  Horror  Musical  Mystery  Romance  Sci-Fi  Thriller  War  \
0             0       0        0        0        0       0         0    0   
1             0       0        0        0        0       0         1    0   
2             0       0        0        0        0       0         1    0   
3             0       0        0        0        0       0         0    0   
4             0       0        0        0        0       0         1    0   
...         ...     ...      ...      ...      ...     ...       ...  ...   
1677          0       0        0        0        0       0         0    0   
1678          0       0        0        0        1       0         1    0   
1679          0       0        0        0        1       0         0    0   
1680          0       0        0        0        0       0         0    0   
1681          0       0        0        0        0       0         0    0   

      Western  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1677        0  
1678        0  
1679        0  
1680        0  
1681        0  

[1682 rows x 24 columns]

In [8]:
users = pd.read_csv('https://raw.githubusercontent.com/han942/vscode/refs/heads/main/datafile/Recsys/ml-100k/u.user',sep='|',
                   names=['userID','age','gender','occupation','zipcode'])
users.head()

userID  age gender  occupation zipcode
0       1   24      M  technician   85711
1       2   53      F       other   94043
2       3   23      M      writer   32067
3       4   24      M  technician   43537
4       5   33      F       other   15213

In [9]:
df = pd.merge(data,items.iloc[:,:2],on='movieID')
user_movie_matrix = pd.pivot_table(data=df,index='userID',columns='movieID',values='ratings')
user_movie_matrix_na = user_movie_matrix.fillna(0)

In [ ]:
def mov2title(ID):
    return items.loc[items['movieID'] == ID, 'title'].values[0]

In [16]:
df

userID  movieID  ratings  timestamp  \
0         196      242        3  881250949   
1          63      242        3  875747190   
2         226      242        5  883888671   
3         154      242        3  879138235   
4         306      242        5  876503793   
...       ...      ...      ...        ...   
99995     840     1674        4  891211682   
99996     655     1640        3  888474646   
99997     655     1637        3  888984255   
99998     655     1630        3  887428735   
99999     655     1641        3  887427810   

                                                   title  
0                                           Kolya (1996)  
1                                           Kolya (1996)  
2                                           Kolya (1996)  
3                                           Kolya (1996)  
4                                           Kolya (1996)  
...                                                  ...  
99995                                  Mamma Roma (1962)  
99996                             Eighth Day, The (1996)  
99997                                  Girls Town (1996)  
99998  Silence of the Palace, The (Saimt el Qusur) (1...  
99999                                    Dadetown (1995)  

[100000 rows x 5 columns]

In [10]:
user_movie_matrix #Sparse Matrix (희소행렬)

movieID  1     2     3     4     5     6     7     8     9     10    ...  \
userID                                                               ...   
1         5.0   3.0   4.0   3.0   3.0   5.0   4.0   1.0   5.0   3.0  ...   
2         4.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   2.0  ...   
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
5         4.0   3.0   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   5.0   NaN  ...   
940       NaN   NaN   NaN   2.0   NaN   NaN   4.0   5.0   3.0   NaN  ...   
941       5.0   NaN   NaN   NaN   NaN   NaN   4.0   NaN   NaN   NaN  ...   
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  ...   
943       NaN   5.0   NaN   NaN   NaN   NaN   NaN   NaN   3.0   NaN  ...   

movieID  1673  1674  1675  1676  1677  1678  1679  1680  1681  1682  
userID                                                               
1         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
2         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
3         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
4         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
5         NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
...       ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  
939       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
940       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
941       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
942       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  
943       NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN   NaN  

[943 rows x 1682 columns]

## Collaborative Filtering

### User-Based Filtering
1. Find Similarity Score btw different users
2. For Target User, Set Neighbors ($K$) to refer
3. Find the Neighbor Similarity Score
4. For Target Items, Predict Ratings for the unknown
    - Compution only needs to be done using observed ratings

$$prediction(a,p) = \bar{r_a} + \frac{\sum{sim(a,b)}*(r_{b,p}-\bar{r_b})}{\sum{|sim(a,b)|}}$$

In [8]:
from sklearn.metrics.pairwise import cosine_similarity
user_movie_matrix = pd.pivot_table(data=df,index='userID',columns='movieID',values='ratings')
user_movie_matrix_na = user_movie_matrix.fillna(0)

user_cos = cosine_similarity(user_movie_matrix_na)

In [9]:
print('영화1의 rating 평균',user_movie_matrix[1].mean())
print('user1의 rating 평균',user_movie_matrix.loc[1].mean())

영화1의 rating 평균 3.8783185840707963
user1의 rating 평균 3.610294117647059


In [10]:
user_movie_matrix_nu = user_movie_matrix_na.to_numpy()

In [38]:
#특정 user_id에 대해 전체 참고
import numpy as np
new_p = user_movie_matrix.copy()

def prediction(user_id,p,b,new_p):
    new_p.loc[user_id,p] = user_movie_matrix_nu[user_id-1].mean() + np.sum(user_cos[user_id-1,b-1] * (user_movie_matrix_nu[b-1,p-1] - user_movie_matrix_nu[b-1].mean())) / np.sum(np.abs(user_cos[user_id-1,b-1]))
user_id = 13
for p in range(1,(len(user_movie_matrix.columns.values)+1)):
    for b in range(1,(len(user_movie_matrix.index.values)+1)):
        if user_movie_matrix_na.loc[user_id,p] == 0:
            if b == user_id:
                pass
            prediction(user_id,p,b,new_p)

KeyboardInterrupt: 

### Item Based CF

## Latent Factor Models

### SVD(MF,Matrix Factorization)

#### 방법1. 기존의 MF 방법
1. 정규분포를 따르는 무작위의 숫자로 구성된 User / Item Latent Matrix P,Q를 구성
2. Nan값이 아닌 Rating을 Test $P,Q^T$의 내적값을 predict로 정의
3. 두 값 사이의 Error를 구해서 Objective Function에 맞는 Optimization 진행
4. 모든 값을 Update 후에 2)~4)의 과정 반복
$$\text{Dimension Guide : } \\ R(m*n),P(m*k),Q(n*k) $$

In [ ]:
import numpy as np
R = np.array(user_movie_matrix)
n_users,n_items = user_movie_matrix.shape
k = 30
P = np.random.normal(scale=0.1/k, size=(n_users,k))
Q = np.random.normal(scale=0.1/k, size=(n_items,k))
epochs = 500
lr = 0.03   #높이면 에러 뜨는듯
reg_param = 0.02 #0.01~0.1
not_nan_ind = [(i,j) for i in range(n_users) for j in range(n_items) if R[i,j]>0]

for epoch in range(epochs):
    np.random.shuffle(not_nan_ind)
    for i,j in not_nan_ind:
        error = R[i,j] - np.dot(P[i,:],Q[j,:].T)
        P[i,:] += lr * (error * Q[j,:] - reg_param * P[i,:])
        Q[j,:] += lr * (error * P[i,:] - reg_param * Q[j,:])
    if epoch % 100 == 0:
        loss = np.sum([((R[i,j]-np.dot(P[i,:],Q[j,:].T))**2) for i,j in not_nan_ind])
        rmse = np.sqrt(loss / len(not_nan_ind))
        print(f"Epoch: {epoch}, Loss: {loss:.4f}, RMSE: {rmse:.4f}")

R_hat = np.dot(P,Q.T)
print("\n예측된 평점 행렬")
print(np.round(R_hat,3))

Epoch: 0, Loss: 112261.4400, RMSE: 1.0595
Epoch: 100, Loss: 23419.2776, RMSE: 0.4839
Epoch: 200, Loss: 22611.6325, RMSE: 0.4755
Epoch: 300, Loss: 22650.6541, RMSE: 0.4759
Epoch: 400, Loss: 22511.5674, RMSE: 0.4745

예측된 평점 행렬
[[3.84 3.19 4.08 ... 1.05 1.69 2.91]
 [3.94 2.91 1.25 ... 0.89 1.89 2.49]
 [3.91 2.87 0.84 ... 1.05 1.12 1.74]
 ...
 [4.74 3.66 2.27 ... 1.16 2.26 2.23]
 [4.62 4.33 4.87 ... 0.8  1.92 2.33]
 [4.03 4.52 1.52 ... 1.21 2.   2.28]]


#### 방법2. Tensorflow 이용
$$ \text{update rule} \\  b_u \leftarrow b_u + \eta*(e_{u,i}-\lambda b_u)\\ p_u \leftarrow p_u+\eta(e_{u,i}q_i-\lambda p_u) $$

- Uncertain for Recommendation Process
    - For Inspected Ratings, Whether to go with the original/predicted Values?
    - For Exceeded Ratings, Do We need to apply Clipping?
- Recommendation Process needed to be Finished

In [11]:
import tensorflow as tf
import numpy as np

R = np.array(user_movie_matrix,dtype='float32')
n_users,n_items = R.shape
lr = 0.0005
K = 30
reg_param = 0.01
epochs = 500

obs_ind = np.array([(i,j) for i in range(n_users) for j in range(n_items) if R[i,j]>0])

P = tf.Variable(tf.random.normal([n_users,K],stddev=0.1),dtype=np.float32)  #Latent Feature Extraction (K)
Q = tf.Variable(tf.random.normal([n_items,K],stddev=0.1),dtype=np.float32)

def predict():
    return tf.matmul(P,Q,transpose_b=True)
def loss_fn():
    pred = predict()
    pred_val = tf.gather_nd(pred,obs_ind)
    R_val = tf.gather_nd(R,obs_ind)
    
    error = R_val - pred_val
    rmse = tf.sqrt(tf.reduce_mean(tf.square(error)))
    loss = tf.reduce_sum(tf.square(error)) #Loss 함수만 제대로 정의하면, Gradient Descent는 따로 정의할 필요 X
    reg_loss = reg_param * (tf.nn.l2_loss(P)+tf.nn.l2_loss(Q))
    
    return loss + reg_loss,rmse
opt = tf.keras.optimizers.SGD(learning_rate=lr)

for epoch in range(epochs+1):
    with tf.GradientTape() as tape:
        loss,rmse = loss_fn()
    grad = tape.gradient(loss,[P,Q])  
    opt.apply_gradients(zip(grad,[P,Q]))
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss:{loss.numpy():.4f}, RMSE:{rmse.numpy():.4f}")

R_pred = predict().numpy()
print("\nPredicted R:")
print(np.round(R_pred,2))

Epoch 0, Loss:1372825.8750, RMSE:3.7052
Epoch 100, Loss:72243.8672, RMSE:0.8497
Epoch 200, Loss:46123.5508, RMSE:0.6787
Epoch 300, Loss:35248.3008, RMSE:0.5931
Epoch 400, Loss:30208.4629, RMSE:0.5489
Epoch 500, Loss:27277.9883, RMSE:0.5215

Predicted R:
[[4.69 3.53 3.59 ... 0.63 0.53 2.48]
 [3.86 3.44 2.29 ... 0.93 1.36 1.76]
 [2.44 3.48 2.89 ... 1.18 1.08 1.89]
 ...
 [4.98 3.6  2.92 ... 0.94 1.13 2.32]
 [4.8  4.25 3.27 ... 0.3  1.1  1.98]
 [5.18 4.08 0.42 ... 1.32 1.5  1.64]]


In [13]:
# obs_ind로 값 불러오는 방법
R_pred[obs_ind[:, 0], obs_ind[:, 1]]
R[obs_ind[:,0],obs_ind[:,1]]

array([5., 3., 4., ..., 3., 3., 3.], dtype=float32)

In [41]:
pd.DataFrame(R_pred).loc[0,:].sort_values(ascending=False)

49      7.385834
407     6.010733
284     5.990698
873     5.946137
168     5.867250
          ...   
1573   -0.055195
1578   -0.093082
1348   -0.102171
976    -0.325161
1501   -0.336340
Name: 0, Length: 1682, dtype: float32

In [ ]:
R_pred_df = pd.DataFrame(R_pred)

0         1         2         3         4         5         6     \
0    4.689913  3.531964  3.585545  3.937963  3.103292  4.428290  4.401823   
1    3.862652  3.442087  2.287360  2.770802  3.564351  5.396686  2.527837   
2    2.444555  3.475006  2.885521  2.688458  2.883836  2.430078  2.616937   
3    4.363518  3.285867  2.215162  3.651012  2.649072  3.620565  5.318117   
4    4.971438  3.218208  1.102734  3.392597  3.597545  1.251181  6.345501   
..        ...       ...       ...       ...       ...       ...       ...   
938  4.819540  4.848808  3.891182  4.375642  4.688023  4.515109  5.275146   
939  4.778694  4.255580  1.287071  2.234573  4.283438  2.475742  4.509081   
940  4.978767  3.600996  2.916365  5.046319  2.892963  4.252689  3.856402   
941  4.798499  4.247694  3.266872  3.597345  4.876666  2.994958  3.167705   
942  5.182549  4.076235  0.423999  3.716459  3.562559  2.409325  3.620283   

         7         8         9     ...      1672      1673      1674  \
0    2.624858  3.744795  2.804779  ...  1.897887  1.657549  1.429182   
1    3.974122  3.352833  2.338225  ...  1.989481  2.126544  1.712226   
2    3.233577  3.193323  3.145700  ...  1.392532  1.627881  1.642393   
3    3.632248  4.201903  4.394157  ...  2.088483  2.818403  1.604002   
4    4.358624  3.807149  4.906024  ...  1.598327  1.931606  1.755021   
..        ...       ...       ...  ...       ...       ...       ...   
938  4.887122  4.720316  4.914187  ...  2.360029  2.472985  1.467852   
939  4.702762  2.756337  3.368954  ...  1.348543  1.749171  1.300443   
940  3.709653  4.634662  4.464357  ...  1.807610  2.375964  1.678120   
941  4.887656  4.135281  3.714921  ...  2.155710  2.201303  1.268304   
942  3.081289  2.947786  3.968814  ...  1.665379  1.618195  2.110689   

         1675      1676      1677      1678      1679      1680      1681  
0    1.550538  1.462794  0.508376  1.344220  0.628086  0.526282  2.484664  
1    1.276011  1.745188  0.554601  1.760136  0.928259  1.357592  1.763133  
2    1.089917  1.725505  0.615461  1.285676  1.181150  1.082789  1.887665  
3    1.802282  1.654778  0.854997  2.274293  1.447879  0.515881  2.235078  
4    1.748720  1.675787  0.481264  1.112171  0.663974  1.090819  2.154672  
..        ...       ...       ...       ...       ...       ...       ...  
938  1.833742  2.007974  0.412763  1.572828  0.927328  1.246744  2.439148  
939  1.284026  1.485166  0.537011  1.598359  0.448981  0.912234  1.595487  
940  1.687765  1.172815  0.527165  1.531482  0.936933  1.129340  2.323511  
941  1.561594  1.893213  0.420450  1.293285  0.303471  1.101815  1.984499  
942  1.978662  0.941314  0.473021  2.241889  1.318185  1.500448  1.638070  

[943 rows x 1682 columns]

In [ ]:
def get_recommendations(userid,itemid,N=10):
    R_hat