# Boolean array indexing

This advanced indexing occurs when obj is an array object of Boolean type, such as may be returned from comparison operators. A single boolean index array is practically identical to x[obj.nonzero()] where, as described above, obj.nonzero() returns a tuple (of length obj.ndim) of integer index arrays showing the True elements of obj. However, it is faster when obj.shape == x.shape.

If obj.ndim == x.ndim, x[obj] returns a 1-dimensional array filled with the elements of x corresponding to the True values of obj. The search order will be row-major, C-style. An index error will be raised if the shape of obj does not match the corresponding dimensions of x, regardless of whether those values are True or False.

A common use case for this is filtering for desired element values. For example, one may wish to select all entries from an array which are not numpy.nan:

In [3]:
import numpy as np
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

In [4]:
np.isnan(x)

array([[False, False],
       [ True, False],
       [ True,  True]])

In [5]:
b = ~np.isnan(x)
b

array([[ True,  True],
       [False,  True],
       [False, False]])

In [6]:
x = np.array([[1,2],[3,4],[5,6]])
x[b]

array([1, 2, 4])

Or wish to add a constant to all negative elements:

If is inefficient

In [7]:
x = np.array([1., -1., -2., 3])
x

array([ 1., -1., -2.,  3.])

In [8]:
b=x[x<0]

In [9]:
x[x<0] = 10
x

array([ 1., 10., 10.,  3.])

In [10]:
x[x < 0] += 20
x

array([ 1., 10., 10.,  3.])

In general if an index includes a Boolean array, the result will be identical to inserting obj.nonzero() into the same position and using the integer array indexing mechanism described above. x[ind_1, boolean_array, ind_2] is equivalent to x[(ind_1,) + boolean_array.nonzero() + (ind_2,)].

If there is only one Boolean array and no integer indexing array present, this is straightforward. Care must only be taken to make sure that the boolean index has exactly as many dimensions as it is supposed to work with.

In general, when the boolean array has fewer dimensions than the array being indexed, this is equivalent to x[b, ...], which means x is indexed by b followed by as many : as are needed to fill out the rank of x. Thus the shape of the result is one dimension containing the number of True elements of the boolean array, followed by the remaining dimensions of the array being indexed:

In [11]:
x = np.arange(35).reshape(5, 7)
b = x > 20
b[:, 5]

array([False, False, False,  True,  True])

In [14]:
b

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [ ]:
print(x[b]) # 1D
print(x[x>20])
x[b[:,5]]


[21 22 23 24 25 26 27 28 29 30 31 32 33 34]
[21 22 23 24 25 26 27 28 29 30 31 32 33 34]


array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [26]:
x[b[:, 5]]

array([[21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

## Problem 1
From an array, select all rows which sum up to less or equal two:

In [69]:
x = np.array([[0, 1], [1, 1], [2, 2]])
x

array([[0, 1],
       [1, 1],
       [2, 2]])

In [ ]:
x[x.sum(axis=1)<=2]

array([[0],
       [1],
       [2]])

Sample Solution 

In [36]:
rowsum = x.sum(-1)
rowsum

array([1, 2, 4])

In [37]:
rowsum <= 2

array([ True,  True, False])

In [38]:
x[rowsum <= 2, :]

array([[0, 1],
       [1, 1]])

below works?  why?
since column matches the shape of boolean

In [39]:
x[rowsum <= 2]

array([[0, 1],
       [1, 1]])

For column sum

In [73]:
colsum = x.sum(0)
colsum<4
x[:,colsum<4]
x[:,(x.sum(axis=0)<4)]

array([[0],
       [1],
       [2]])

## Problem 2

In [2]:
import numpy as np

In [3]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

which is same as 

In [52]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [19]:
s = np.arange(12).reshape(4,3)
s

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [24]:
s[np.ix_([0,1],[1,2])]

array([[1, 2],
       [4, 5]])

Use boolean indexing to select all rows adding up to an even number. At the same time columns 0 and 2 should be selected with an advanced integer index. Using the ix_ function this can be done with:

In [28]:
np.ix_?

In [5]:
np.ix_([0,1,3], [2, 4])

(array([[0],
        [1],
        [3]]),
 array([[2, 4]]))

In [7]:
rows = (x.sum(-1) % 2) == 0
rows

array([False,  True, False,  True])

In [11]:
columns = [0, 2]
np.ix_(rows, columns)

(array([[1],
        [3]]),
 array([[0, 2]]))

In [12]:
np.ix_(rows, columns)

(array([[1],
        [3]]),
 array([[0, 2]]))

In [13]:
x[np.ix_(rows, columns)]

array([[ 3,  5],
       [ 9, 11]])

Without the np.ix_ call, only the diagonal elements would be selected.

In [59]:
x[rows,columns]

array([ 3, 11])

Or without np.ix_ (compare the integer array examples):

In [48]:
rows = rows.nonzero()[0]
rows

array([1, 3])

In [61]:
rows[:, np.newaxis]

array([[1],
       [3]])

In [50]:
l = np.array([0,1])

l[:,np.newaxis]

array([[0],
       [1]])

In [62]:
x[rows[:, np.newaxis], columns]

array([[ 3,  5],
       [ 9, 11]])

## Problem 3 (Expanding 3d boolean)

Use a 2-D boolean array of shape (2, 3) with four True elements to select rows from a 3-D array of shape (2, 3, 5) results in a 2-D result of shape (4, 5):

In [57]:
x = np.arange(30).reshape(2, 3, 5)
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]],

       [[15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]]])

In [62]:
b = np.array([[True, True, False], [False, True, True]])
b


array([[ True,  True, False],
       [False,  True,  True]])

In [67]:
x[b]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [1]:
import pandas as pd
import numpy as np

UsageError: Line magic function `%help` not found.
