# Numpy
The fundamental package for scientific computing with Python

**1. Powerful N-dimensional arrays**\
Fast and versatile, the NumPy vectorization, indexing, and broadcasting concepts are the de-facto standards of array computing today.

**2. Numerical computing tools**\
NumPy offers comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.

**3. Interoperable**\
NumPy supports a wide range of hardware and computing platforms, and plays well with distributed, GPU, and sparse array libraries.

**4. Performant**\
The core of NumPy is well-optimized C code. Enjoy the flexibility of Python with the speed of compiled code.


In [2]:
import numpy as np
import time

a = np.random.rand(1000000) #1M
b = np.random.rand(1000000)

c = 0
tic = time.time()
for i in range(1000000):
    c += a[i] * b[i]
toc = time.time()

print("For loop: " + str(1000*(toc-tic)) + "ms")

For loop: 218.81961822509766ms


In [ ]:
tic = time.time()
c = np.dot(a, b)
toc = time.time()

print("Vectorised version: " + str(1000*(toc-tic)) + "ms")

Vectorised version: 47.73521423339844ms


**5. Easy to use**\
NumPy’s high level syntax makes it accessible and productive for programmers from any background or experience level.

In [6]:
import numpy as np
a = np.array(([1,2],[3,4]))
print(f'{a}\n')

b = np.array(([5,6],[7,8]))
print(b)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [12]:
print('element-wise mat multiplication: \n',a*b)
print('matrix addition: \n',a+b)
print('matrix subtraction: \n',a-b)

element-wise mat multiplication: 
 [[ 5 12]
 [21 32]]
matrix addition: 
 [[ 6  8]
 [10 12]]
matrix subtraction: 
 [[-4 -4]
 [-4 -4]]


**not element-wise multiplication** / matrix multiplication?

In [12]:
np.matmul(a,b)

array([[19, 22],
       [43, 50]])

$\det{a}$

In [13]:
np.linalg.det(a)

-2.0000000000000004

$A^{-1}$

In [14]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

```python
np.zeros / np.ones
```

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((3,1))

array([[0.],
       [0.],
       [0.]])

In [17]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [14]:
np.ones(1)

array([1.])

In [15]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [3]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

## List vs ArrayList
* ArrayList is subjected under numpy package

In [18]:
a = [1, 2]
a

[1, 2]

In [19]:
type(a)

list

In [20]:
b = np.array([1,2])

In [21]:
type(b)

numpy.ndarray

In [22]:
np.asarray(a)

array([1, 2])

In [23]:
np.array(a)

array([1, 2])

what about back to list ? 

In [24]:
np.array([[1,2,3],[4,5,6]]).tolist()

[[1, 2, 3], [4, 5, 6]]

## basic indexing

In [16]:
x = np.arange(5,10)
x

array([5, 6, 7, 8, 9])

arange: Return evenly spaced values within a given interval.

In [27]:
np.arange(5,10,2)

array([5, 7, 9])

In [28]:
x[0]

5

In [29]:
x[3]

8

last index?  Let's count....

In [30]:
x[4]

9

don't want to count 

In [31]:
x[-1]

9

any number? 

In [ ]:
x[9] #Range IndexError

IndexError: index 9 is out of bounds for axis 0 with size 5

In [ ]:
x[-1.0] # dtype IndexError

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [34]:
x[-2]

8

## basic slicing and striding

In [36]:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])    # np.arange(10)

In [37]:
x[1:7:3]   #i,j,k :  i is the starting index, j is the stopping index, and k is the step 

array([1, 4])

In [38]:
x[1:7]

array([1, 2, 3, 4, 5, 6])

In [39]:
x[:4]

array([0, 1, 2, 3])

In [40]:
x[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
x[-1]

9

In [42]:
x[:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [43]:
x[-3:]

array([7, 8, 9])

## advanced indexing

Integer array indexing

In [44]:
x = np.arange(5,15)
x

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
x[np.array([4,4,2])]

array([9, 9, 7])

In [ ]:
x[[4,4,4,4,4,2]] #Performs corresponding index

array([9, 9, 9, 9, 9, 7])

## repeat

In [23]:
a = np.array(([1,2,5,4],[3,4,1,7]))
a.shape

(2, 4)

$A = \begin{bmatrix}
   1 & 2 & 5 & 4 \\
   3 & 4 & 1 & 7
\end{bmatrix}$

In [28]:
np.mean(a,axis=0),np.mean(a,axis=1),np.mean(a)

(array([2. , 3. , 3. , 5.5]), array([3.  , 3.75]), np.float64(3.375))

In [29]:
np.max(a,axis=0),np.max(a,axis=1),np.max(a)

(array([3, 4, 5, 7]), array([5, 7]), np.int64(7))

In [19]:
np.repeat(a, 2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [51]:
np.repeat(a, 2,axis=-1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

## flatten

In [52]:
a.flatten()

array([1, 2, 3, 4])

In [4]:
b = np.array(([5,6],[7,8]))

In [5]:
b.flatten()

array([5, 6, 7, 8])

## concatenate

In [55]:
np.concatenate((a,b))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [56]:
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [57]:
np.concatenate((a,b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## transpose

In [ ]:
np.transpose(a)

## reshape

In [ ]:
np.arange(12).reshape((2,-1,3))

In [ ]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a,6)

In [ ]:
np.reshape(a, (3,2))

In [ ]:
np.reshape(a, (3,-1,))

## squeeze

remove axes of length one from input

In [ ]:
t = np.arange(6)

In [ ]:
t.shape

In [ ]:
t = np.reshape(t,(6,1))

In [ ]:
t.shape

In [ ]:
np.squeeze(t)

## stack

Join a sequence of arrays along a new axis.

In [ ]:
array = np.random.randn(3, 4) 
array

In [ ]:
arrays = [np.random.randn(3, 4) for _ in range(10)]
arrays

In [ ]:
arrays

In [ ]:
np.stack(arrays, axis=0).shape

In [ ]:
np.stack(arrays, axis=1).shape

In [ ]:
np.stack(arrays, axis=2).shape

## vstack

stack arrays in sequence vertically (row wise)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
np.vstack((a,b))

In [ ]:
a = np.array([[1], [2], [3]])
b = np.array([[4], [5], [6]])

In [ ]:
np.vstack((a,b))

## hstack

Stack arrays in sequence horizontally (column wise)

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [ ]:
np.hstack((a,b))

In [ ]:
a = np.array([[1],[2],[3]])
b = np.array([[4],[5],[6]])

In [ ]:
np.hstack((a,b))

## concat

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
print(a)

In [ ]:
print(b)

In [ ]:
b.shape

In [ ]:
c = np.array([5,6])

In [ ]:
print(c)

In [ ]:
c.shape

In [ ]:
np.concatenate((a, b), axis=0)

In [ ]:
np.concatenate((a, b), axis=1)

In [ ]:
np.concatenate((a, b.T), axis=1)

In [ ]:
np.concatenate((a, c), axis=0)

In [ ]:
np.vstack((a,c))

why work? 

This is equivalent to concatenation along the first axis after 1-D arrays of shape (N,) have been reshaped to (1,N).

## split

Split an array into multiple sub-arrays as views into ary.

In [ ]:
x = np.arange(9.0)

In [ ]:
np.split(x, 3)

In [ ]:
np.split(x, 4)

In [ ]:
x = np.arange(8.0)
np.split(x, [3, 5, 6, 10])

## vsplit

In [ ]:
x = np.arange(8.0).reshape(2, 2, 2)
x

In [ ]:
np.vsplit(x, 2)

array is always split along the first axis regardless of the array dimension.

## hsplit

In [ ]:
x = np.arange(8.0).reshape(2, 2, 2)
x

In [ ]:
np.hsplit(x, 2)

Split an array into multiple sub-arrays horizontally (column-wise).
hsplit is equivalent to split with axis=1

## flip

Reverse the order of elements in an array along the given axis.

The shape of the array is preserved, but the elements are reordered.

In [ ]:
A = np.arange(8).reshape((2,2,2))

In [ ]:
A

In [ ]:
np.flip(A,0)

In [ ]:
np.flip(A,1)

In [ ]:
np.flip(A,2)

## trim_zeros

Trim the leading and/or trailing zeros from a 1-D array or sequence.

In [ ]:
a = np.array((0, 0, 0, 1, 2, 3, 0, 2, 1, 0))

In [ ]:
np.trim_zeros(a)

In [ ]:
np.trim_zeros(a,'f')

In [ ]:
np.trim_zeros(a,'b')

In [ ]:
np.ma.masked_equal(a,0)