In [3]:
# movielens 100K

#SVD 알아오기
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd
from pathlib import Path

path = Path('../../../datafile/Recsys/ml-100k')
raw_data = pd.read_csv(path /'u.data',sep='\t',
                   usecols=[0,1,2],names=['user','item','rating'],
                   dtype={'user':int,'item':int,'rating':float})

user_id = raw_data['user'].unique().tolist()

raw_data.head()

train,test = train_test_split(raw_data,test_size=0.2,random_state=42)
R_train = pd.pivot_table(train,values='rating',index='item',columns='user')

In [4]:
train

user  item  rating
75220   807  1411     1.0
48955   474   659     5.0
44966   463   268     4.0
13568   139   286     4.0
92727   621   751     4.0
...     ...   ...     ...
6265    216   231     2.0
54886   343   276     5.0
76820   437   475     3.0
860     284   322     3.0
15795   222   200     3.0

[80000 rows x 3 columns]

381
602
431
875
182
1074
286
496
15
184
864
568
1197
99
31
286
14
176
618
568
176
476
82
492
303
408
483
180
109
156
1281
2
979
214
1165
245
326
651
95
45
318
684
682
38
257
77
1091
647
230
636
276
386
519
1086
205
187
234
934
240
742
547
431
273
1448
195
204
569
235
182
810
1015
845
324
26
219
1016
28
628
1446
288
395
568
100
83
428
289
278
111
271
269
1142
175
473
125
647
121
190
610
11
50
844
298
182
125
919
1281
195
381
845
762
97
1210
1059
9
214
172
68
276
106
1197
700
737
1051
1115
740
1033
1109
234
414
1333
559
268
990
230
428
1590
741
284
262
11
654
1063
50
1
1054
309
290
69
931
28
780
300
346
463
272
288
419
59
233
411
301
855
202
989
397
429
466
572
797
251
12
469
435
528
312
313
1011
56
318
118
64
915
133
55
1511
362
1183
380
333
209
109
333
121
222
117
197
43
1324
4
137
7
527
404
222
554
173
49
155
141
1028
218
2
25
325
367
938
249
294
412
909
373
344
405
286
739
33
1316
797
191
631
1609
70
932
14
399
276
569
13
651
117
180
301
292
845
1404
118
578
241
172
192
1210
343
623


In [5]:
uilist_test = list(zip(test['user'],test['item']))
pred_list = []
for ind in uilist_test:
    pred_list.append(R_train[ind[0],ind[1]])
pred_list

KeyError: (877, 381)

In [ ]:
pd.DataFrame(R_train)

Index([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,
       ...
       934, 935, 936, 937, 938, 939, 940, 941, 942, 943],
      dtype='int64', name='user', length=943)

In [ ]:
user_item_mat = pd.pivot_table(data=raw_data,values='rating',columns='user',index='item')
user_item_mat

user  1    2    3    4    5    6    7    8    9    10   ...  934  935  936  \
item                                                    ...                  
1     5.0  4.0  NaN  NaN  4.0  4.0  NaN  NaN  NaN  4.0  ...  2.0  3.0  4.0   
2     3.0  NaN  NaN  NaN  3.0  NaN  NaN  NaN  NaN  NaN  ...  4.0  NaN  NaN   
3     4.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  4.0   
4     3.0  NaN  NaN  NaN  NaN  NaN  5.0  NaN  NaN  4.0  ...  5.0  NaN  NaN   
5     3.0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1678  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
1679  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
1680  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
1681  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   
1682  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  ...  NaN  NaN  NaN   

user  937  938  939  940  941  942  943  
item                                     
1     NaN  4.0  NaN  NaN  5.0  NaN  NaN  
2     NaN  NaN  NaN  NaN  NaN  NaN  5.0  
3     NaN  NaN  NaN  NaN  NaN  NaN  NaN  
4     NaN  NaN  NaN  2.0  NaN  NaN  NaN  
5     NaN  NaN  NaN  NaN  NaN  NaN  NaN  
...   ...  ...  ...  ...  ...  ...  ...  
1678  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1679  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1680  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1681  NaN  NaN  NaN  NaN  NaN  NaN  NaN  
1682  NaN  NaN  NaN  NaN  NaN  NaN  NaN  

[1682 rows x 943 columns]

In [4]:
import numpy as np

# 분해할 행렬 A 생성
A = np.array([
    [3, 1, 1],
    [-1, 3, 1]
])

print("--- 원본 행렬 A ---")
print(A)

U, s, Vt = np.linalg.svd(A)

print("\n--- 분해된 행렬들 ---")
print("U의 모양:", U.shape)
print("s의 모양:", s.shape) # 1차원 배열임에 주의!
print("Vt의 모양:", Vt.shape)

# s를 대각 행렬 Σ로 재구성
# 원본 A의 크기에 맞게 0을 채워줌
Sigma = np.zeros(A.shape)
Sigma[:len(s), :len(s)] = np.diag(s)

k = 2
U_k = U[:,:k]
Sigma_k = Sigma[:k,:k]
Vt_k = Vt[:k,:]

print("\n--- 재구성된 대각 행렬 Σ ---")
print(Sigma)

# U, Σ, Vt를 다시 곱해서 A를 복원
A_restored = U @ Sigma @ Vt  # @는 행렬 곱셈 연산자
A_k_restored = U_k @ Sigma_k @ Vt_k

print("\n--- 복원된 행렬 A,A_k ---")
print('Truncated SVD: ',A_k_restored.round(3))
print('Full-SVD : ',A_restored.round(3)) # 부동소수점 오차를 감안해 반올림

--- 원본 행렬 A ---
[[ 3  1  1]
 [-1  3  1]]

--- 분해된 행렬들 ---
U의 모양: (2, 2)
s의 모양: (2,)
Vt의 모양: (3, 3)

--- 재구성된 대각 행렬 Σ ---
[[3.46410162 0.         0.        ]
 [0.         3.16227766 0.        ]]

--- 복원된 행렬 A,A_k ---
Truncated SVD:  [[ 3.  1.  1.]
 [-1.  3.  1.]]
Full-SVD :  [[ 3.  1.  1.]
 [-1.  3.  1.]]
